-- https://en.wikipedia.org/wiki/List_of_DNS_record_types
-- https://www.iana.org/assignments/dns-parameters/dns-parameters.xhtml
CREATE TABLE IF NOT EXISTS DomainNameSystemResourceRecordTypes
(
    name            VARCHAR(16)         NOT NULL PRIMARY KEY,
    typeNumber      SMALLINT UNSIGNED   NOT NULL, -- Cannot be UNIQUE, because newer RR types have inherited obsoleted numbers.
    definingRFC     SMALLINT UNSIGNED   NULL,
    nameMeaning     TINYTEXT            NULL,
    description     MEDIUMTEXT          NULL,
    pseudoRecord    BOOLEAN             NULL,
    obsolete        BOOLEAN             NULL,
    obsoletingRFC   SMALLINT UNSIGNED   NULL
);

INSERT IGNORE INTO DomainNameSystemResourceRecordTypes
VALUES
	('A', 1, 1035, 'Address record', 'Returns a 32-bit IPv4 address, most commonly used to map hostnames to an IP address of the host, but it is also used for DNSBLs, storing subnet masks in RFC 1101, etc.', FALSE, FALSE, NULL),
	('AAAA', 28, 3596, 'IPv6 address record', 'Returns a 128-bit IPv6 address, most commonly used to map hostnames to an IP address of the host.', FALSE, FALSE, NULL),
	('AFSDB', 18, 1183, 'AFS database record', 'Location of database servers of an AFS cell. This record is commonly used by AFS clients to contact AFS cells outside their local domain. A subtype of this record is used by the obsolete DCE/DFS file system.', FALSE, FALSE, NULL),
	('APL', 42, 3123, 'Address Prefix List', 'Specify lists of address ranges, e.g. in CIDR format, for various address families. Experimental.', FALSE, FALSE, NULL),
	('CAA', 257, 6844, 'Certification Authority Authorization', 'DNS Certification Authority Authorization, constraining acceptable CAs for a host/domain', FALSE, FALSE, NULL),
	('CDNSKEY', 60, 7344, 'Child copy of DNSKEY record, for transfer to', 'parent', FALSE, FALSE, NULL),
	('CDS', 59, 7344, 'Child DS', 'Child copy of DS record, for transfer to parent', FALSE, FALSE, NULL),
	('CERT', 37, 4398, 'Certificate record', 'Stores PKIX, SPKI, PGP, etc.', FALSE, FALSE, NULL),
	('CNAME', 5, 1035, 'Canonical name record', 'Alias of one name to another: the DNS lookup will continue by retrying the lookup with the new name.', FALSE, FALSE, NULL),
	('DHCID', 49, 4701, 'DHCP identifier', 'Used in conjunction with the FQDN option to DHCP', FALSE, FALSE, NULL),
	('DLV', 32769, 4431, 'DNSSEC Lookaside Validation record', 'For publishing DNSSEC trust anchors outside of the DNS delegation chain. Uses the same format as the DS record. RFC 5074 describes a way of using these records.', FALSE, FALSE, NULL),
	('DNAME', 39, 6672, NULL, 'Alias for a name and all its subnames, unlike CNAME, which is an alias for only the exact name. Like a CNAME record, the DNS lookup will continue by retrying the lookup with the new name.', FALSE, FALSE, NULL),
	('DNSKEY', 48, 4034, 'DNS Key record', 'The key record used in DNSSEC. Uses the same format as the KEY record.', FALSE, FALSE, NULL),
	('DS', 43, 4034, 'Delegation signer', 'The record used to identify the DNSSEC signing key of a delegated zone', FALSE, FALSE, NULL),
	('HIP', 55, 8005, 'Host Identity Protocol', 'Method of separating the end-point identifier and locator roles of IP addresses.', FALSE, FALSE, NULL),
	('IPSECKEY', 45, 4025, 'IPsec Key', 'Key record that can be used with IPsec', FALSE, FALSE, NULL),
	('KX', 36, 2230, 'Key Exchanger record', 'Used with some cryptographic systems (not including DNSSEC) to identify a key management agent for the associated domain-name. Note that this has nothing to do with DNS Security. It is Informational status, rather than being on the IETF standards-track. It has always had limited deployment, but is still in use.', FALSE, FALSE, NULL),
	('LOC', 29, 1876, 'Location record', 'Specifies a geographical location associated with a domain name', FALSE, FALSE, NULL),
	('MX', 15, 1035, 'Mail exchange record', 'Maps a domain name to a list of message transfer agents for that domain', FALSE, FALSE, NULL),
	('NAPTR', 35, 3403, 'Naming Authority Pointer', 'Allows regular-expression-based rewriting of domain names which can then be used as URIs, further domain names to lookups, etc.', FALSE, FALSE, NULL),
	('NS', 2, 1035, 'Name server record', 'Delegates a DNS zone to use the given authoritative name servers', FALSE, FALSE, NULL),
	('NSEC', 47, 4034, 'Next Secure record', 'Part of DNSSEC—used to prove a name does not exist. Uses the same format as the (obsolete) NXT record.', FALSE, FALSE, NULL),
	('NSEC3', 50, 5155, 'Next Secure record version 3', 'An extension to DNSSEC that allows proof of nonexistence for a name without permitting zonewalking', FALSE, FALSE, NULL),
	('NSEC3PARAM', 51, 5155, 'NSEC3 parameters', 'Parameter record for use with NSEC3', FALSE, FALSE, NULL),
	('OPENPGPKEY', 61, 7929, 'OpenPGP public key record', 'A DNS-based Authentication of Named Entities (DANE) method for publishing and locating OpenPGP public keys in DNS for a specific email address using an OPENPGPKEY DNS resource record.', FALSE, FALSE, NULL),
	('PTR', 12, 1035, 'Pointer record', 'Pointer to a canonical name. Unlike a CNAME, DNS processing stops and just the name is returned. The most common use is for implementing reverse DNS lookups, but other uses include such things as DNS-SD.', FALSE, FALSE, NULL),
	('RRSIG', 46, 4034, 'DNSSEC signature', 'Signature for a DNSSEC-secured record set. Uses the same format as the SIG record.', FALSE, FALSE, NULL),
	('RP', 17, 1183, 'Responsible Person', 'Information about the responsible person(s) for the domain. Usually an email address with the @ replaced by a .', FALSE, FALSE, NULL),
	('SOA', 6, 1035, 'Start of [a zone of] authority record', 'Specifies authoritative information about a DNS zone, including the primary name server, the email of the domain administrator, the domain serial number, and several timers relating to refreshing the zone.', FALSE, FALSE, NULL),
	('SRV', 33, 2782, 'Service locator', 'Generalized service location record, used for newer protocols instead of creating protocol-specific records such as MX.', FALSE, FALSE, NULL),
	('SSHFP', 44, 4255, 'SSH Public Key Fingerprint', 'Resource record for publishing SSH public host key fingerprints in the DNS System, in order to aid in verifying the authenticity of the host. RFC 6594 defines ECC SSH keys and SHA-256 hashes. See the IANA SSHFP RR parameters registry for details.', FALSE, FALSE, NULL),
    ('TA', 32768, NULL, 'DNSSEC Trust Authorities', 'Part of a deployment proposal for DNSSEC without a signed DNS root. See the IANA database and Weiler Spec for details. Uses the same format as the DS record.', FALSE, FALSE, NULL),
	('TKEY', 249, 2930, 'Transaction Key record', 'A method of providing keying material to be used with TSIG that is encrypted under the public key in an accompanying KEY RR.[10]', FALSE, FALSE, NULL),
	('TLSA', 52, 6698, 'TLSA certificate association', 'A record for DANE. RFC 6698 defines "The TLSA DNS resource record is used to associate a TLS server certificate or public key with the domain name where the record is found, thus forming a ''TLSA certificate association''.', FALSE, FALSE, NULL),
	('TSIG', 250, 2845, 'Transaction Signature', 'Can be used to authenticate dynamic updates as coming from an approved client, or to authenticate responses as coming from an approved recursive name server[11] similar to DNSSEC.', FALSE, FALSE, NULL),
	('TXT', 16, 1035, 'Text record', 'Originally for arbitrary human-readable text in a DNS record. Since the early 1990s, however, this record more often carries machine-readable data, such as specified by RFC 1464, opportunistic encryption, Sender Policy Framework, DKIM, DMARC, DNS-SD, etc.', FALSE, FALSE, NULL),
	('URI', 256, 7553, 'Uniform Resource Identifier', 'Can be used for publishing mappings from hostnames to URIs.', FALSE, FALSE, NULL),
	('*', 255, 1035, 'All cached records', 'Returns all records of all types known to the name server. If the name server does not have any information on the name, the request will be forwarded on. The records returned may not be complete. For example, if there is both an A and an MX for a name, but the name server has only the A record cached, only the A record will be returned. Sometimes referred to as "ANY", for example in Windows nslookup and Wireshark.', TRUE, FALSE, NULL),
	('AXFR', 252, 1035, 'Authoritative Zone Transfer', 'Transfer entire zone file from the master name server to secondary name servers.', TRUE, FALSE, NULL),
	('IXFR', 251, 1996, 'Incremental Zone Transfer', 'Requests a zone transfer of the given zone but only differences from a previous serial number. This request may be ignored and a full (AXFR) sent in response if the authoritative server is unable to fulfill the request due to configuration or lack of required deltas.', TRUE, FALSE, NULL),
	('OPT', 41, 6891, 'Option', 'This is a "pseudo DNS record type" needed to support EDNS', TRUE, FALSE, NULL),
	('MD', 3, 883, NULL, 'Mail destination (MD) and mail forwarder (MF) records; MAILA is not an actual record type, but a query type which returns MF and/or MD records. RFC 973 replaced these records with the MX record.', FALSE, TRUE, 973),
	('MF', 4, 883, NULL, 'Mail destination (MD) and mail forwarder (MF) records; MAILA is not an actual record type, but a query type which returns MF and/or MD records. RFC 973 replaced these records with the MX record.', FALSE, TRUE, 973),
	('MAILA', 254, 883, NULL, 'Mail destination (MD) and mail forwarder (MF) records; MAILA is not an actual record type, but a query type which returns MF and/or MD records. RFC 973 replaced these records with the MX record.', FALSE, TRUE, 973),
	('MB', 7, 883, NULL, 'Records to publish mailing list subscriber lists in the DNS: MB(7), MG(8), MR(9), MINFO(14); MAILB (253) is a query code which returns one of the aforementioned records. The intent, as specified by RFC 883, was for MB to replace the SMTP VRFY command, MG to replace the SMTP EXPN command, and MR to replace the "551 User Not Local" SMTP error. Later, RFC 2505 recommended that both the VRFY and EXPN commands be disabled, making the use of MB and MG unlikely to ever be adopted. They were classified as experimental by RFC 1035.', FALSE, TRUE, NULL),
	('MG', 8, 883, NULL, 'Records to publish mailing list subscriber lists in the DNS: MB(7), MG(8), MR(9), MINFO(14); MAILB (253) is a query code which returns one of the aforementioned records. The intent, as specified by RFC 883, was for MB to replace the SMTP VRFY command, MG to replace the SMTP EXPN command, and MR to replace the "551 User Not Local" SMTP error. Later, RFC 2505 recommended that both the VRFY and EXPN commands be disabled, making the use of MB and MG unlikely to ever be adopted. They were classified as experimental by RFC 1035.', FALSE, TRUE, NULL),
	('MR', 9, 883, NULL, 'Records to publish mailing list subscriber lists in the DNS: MB(7), MG(8), MR(9), MINFO(14); MAILB (253) is a query code which returns one of the aforementioned records. The intent, as specified by RFC 883, was for MB to replace the SMTP VRFY command, MG to replace the SMTP EXPN command, and MR to replace the "551 User Not Local" SMTP error. Later, RFC 2505 recommended that both the VRFY and EXPN commands be disabled, making the use of MB and MG unlikely to ever be adopted. They were classified as experimental by RFC 1035.', FALSE, TRUE, NULL),
	('MINFO', 14, 883, NULL, 'Records to publish mailing list subscriber lists in the DNS: MB(7), MG(8), MR(9), MINFO(14); MAILB (253) is a query code which returns one of the aforementioned records. The intent, as specified by RFC 883, was for MB to replace the SMTP VRFY command, MG to replace the SMTP EXPN command, and MR to replace the "551 User Not Local" SMTP error. Later, RFC 2505 recommended that both the VRFY and EXPN commands be disabled, making the use of MB and MG unlikely to ever be adopted. They were classified as experimental by RFC 1035.', FALSE, TRUE, NULL),
	('MAILB', 253, 883, NULL, 'Records to publish mailing list subscriber lists in the DNS: MB(7), MG(8), MR(9), MINFO(14); MAILB (253) is a query code which returns one of the aforementioned records. The intent, as specified by RFC 883, was for MB to replace the SMTP VRFY command, MG to replace the SMTP EXPN command, and MR to replace the "551 User Not Local" SMTP error. Later, RFC 2505 recommended that both the VRFY and EXPN commands be disabled, making the use of MB and MG unlikely to ever be adopted. They were classified as experimental by RFC 1035.', FALSE, TRUE, NULL),
	('WKS', 11, 883, NULL, 'Record to describe well-known services supported by a host. Not used in practice. The current recommendation and practice is to determine whether a service is supported on an IP address by trying to connect to it. SMTP is even prohibited from using WKS records in MX processing.', FALSE, TRUE, 1123),
	('NB', 32, 1002, NULL, 'Mistakes: NB(32), NBSTAT(33) (from RFC 1002); the numbers are now assigned to NIMLOC and SRV.', FALSE, TRUE, NULL),
	('NBSTAT', 33, 1002, NULL, 'Mistakes: NB(32), NBSTAT(33) (from RFC 1002); the numbers are now assigned to NIMLOC and SRV.', FALSE, TRUE, NULL),
	('NULL', 10, 883, NULL, 'NULL(10) (RFC 883 defined "completion queries" (opcode 2 and maybe 3) which used this record, RFC 1035 later reassigned opcode 2 to be "status" and reserved opcode 3.)', FALSE, TRUE, 1035),
	('A6', 38, 2874, NULL, 'Defined as part of early IPv6 but downgraded to experimental by RFC 3363: A6(38), Later downgraded to historic in RFC 6563.', FALSE, TRUE, 6563),
	('NXT', 30, 2065, NULL, 'Part of the first version of DNSSEC (RFC 2065). Obsoleted by DNSSEC updates (RFC 3755): NXT(30). At the same time, the domain of applicability for KEY and SIG was also limited to not include DNSSEC use.', FALSE, TRUE, 3755),
	('KEY', 25, 2065, 'Key record', 'Part of the first version of DNSSEC (RFC 2065). Obsoleted by DNSSEC updates (RFC 3755): NXT(30). At the same time, the domain of applicability for KEY and SIG was also limited to not include DNSSEC use.', FALSE, TRUE, 3755),
	('SIG', 24, 2065, 'Signature', 'Part of the first version of DNSSEC (RFC 2065). Obsoleted by DNSSEC updates (RFC 3755): NXT(30). At the same time, the domain of applicability for KEY and SIG was also limited to not include DNSSEC use.', FALSE, TRUE, 3755),
	('HINFO', 13, 883, NULL, 'Record intended to provide information about host CPU type and operating system. It was intended to allow protocols to optimize processing when communicating with similar peers', FALSE, TRUE, NULL),
	('X25', 19, NULL, NULL, 'Not in current use by any notable application', FALSE, TRUE, NULL),
	('ISDN', 20, NULL, NULL, 'Not in current use by any notable application', FALSE, TRUE, NULL),
	('RT', 21, NULL, NULL, 'Not in current use by any notable application', FALSE, TRUE, NULL),
	('NSAP', 22, NULL, NULL, 'Not in current use by any notable application', FALSE, TRUE, NULL),
	('NSAP-PTR', 23, NULL, NULL, 'Not in current use by any notable application', FALSE, TRUE, NULL),
	('PX', 26, NULL, NULL, 'Not in current use by any notable application', FALSE, TRUE, NULL),
	('EID', 31, NULL, NULL, 'Not in current use by any notable application', FALSE, TRUE, NULL),
	('NIMLOC', 32, NULL, NULL, 'Not in current use by any notable application', FALSE, TRUE, NULL),
	('ATMA', 34, NULL, NULL, 'Not in current use by any notable application', FALSE, TRUE, NULL),
	('SINK', 40, NULL, NULL, 'Defined by the Kitchen Sink internet draft, but never made it to RFC status: SINK(40)', FALSE, TRUE, NULL),
	('GPOS', 27, NULL, NULL, 'A more limited early version of the LOC record: GPOS(27)', FALSE, TRUE, NULL),
	('UINFO', 100, NULL, NULL, 'IANA reserved, no RFC documented them [2] and support was removed from BIND in the early 90s: UINFO(100), UID(101), GID(102), UNSPEC(103)', FALSE, TRUE, NULL),
	('UID', 101, NULL, NULL, 'IANA reserved, no RFC documented them [2] and support was removed from BIND in the early 90s: UINFO(100), UID(101), GID(102), UNSPEC(103)', FALSE, TRUE, NULL),
	('GID', 102, NULL, NULL, 'IANA reserved, no RFC documented them [2] and support was removed from BIND in the early 90s: UINFO(100), UID(101), GID(102), UNSPEC(103)', FALSE, TRUE, NULL),
	('UNSPEC', 103, NULL, NULL, 'IANA reserved, no RFC documented them [2] and support was removed from BIND in the early 90s: UINFO(100), UID(101), GID(102), UNSPEC(103)', FALSE, TRUE, NULL),
	('SPF', 99, 4408, NULL, 'SPF(99) (from RFC 4408) was specified as part of the Sender Policy Framework protocol as an alternative to storing SPF data in TXT records, using the same format. It was later found that the majority of SPF deployments lack proper support for this record type, and support for it was discontinued in RFC 7208.', FALSE, TRUE, 7208)
;